import {createSceneNavigator,RESTS} from './motion-lab/navigation.mjs';
const story=document.querySelector('.cinema'),pin=story.querySelector('.cinema-pin'),site=story.querySelector('.cinema-site'),intro=story.querySelector('.cinema-intro');const reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width:760px)');let metrics={},frame=0,enabled=false;
const clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>x*x*(3-2*x);function progress(){return clamp((scrollY-metrics.top)/metrics.travel)}
function measure(){const header=document.querySelector('.site-header').offsetHeight;metrics={top:story.getBoundingClientRect().top+scrollY-header,travel:Math.max(1,story.offsetHeight-pin.offsetHeight),w:pin.clientWidth,h:pin.clientHeight};schedule()}
const nav=createSceneNavigator({getProgress:progress,seek:p=>{scrollTo({top:metrics.top+p*metrics.travel,behavior:'instant'});schedule()},isEnabled:()=>enabled&&scrollY>=metrics.top-2&&scrollY<=metrics.top+metrics.travel+2,now:()=>performance.now(),requestFrame:requestAnimationFrame,cancelFrame:cancelAnimationFrame});
function draw(){frame=0;if(!enabled)return;const p=progress();const rects=mobile.matches?[[.08,.45,.84,.46],[.025,.045,.95,.865],[.08,.40,.84,.49],[.25,.38,.5,.53]]:[[.205,.565,.59,.355],[.025,.035,.95,.89],[.45,.13,.51,.74],[.62,.09,.255,.82]];let n=RESTS.findIndex((x,i)=>i<3&&p>=x&&p<=RESTS[i+1]);if(n<0)n=2;let t=ease(clamp((p-RESTS[n])/(RESTS[n+1]-RESTS[n])));const rect=rects[n].map((x,i)=>x+(rects[n+1][i]-x)*t);site.style.transform=`translate3d(${rect[0]*metrics.w}px,${rect[1]*metrics.h}px,0)`;site.style.width=rect[2]*metrics.w+'px';site.style.height=rect[3]*metrics.h+'px';site.style.borderRadius=(p>.56?8+ease((p-.56)/.44)*20:8)+'px';const out=1-ease(clamp(p/.18));intro.style.opacity=out;intro.style.transform=`translateY(${-70*(1-out)}px)`;intro.inert=out<.2;intro.style.visibility=out<.01?'hidden':'visible';story.querySelectorAll('.cinema-side').forEach((el,i)=>{el.style.opacity=out;el.style.transform=`translateX(${(i?1:-1)*(1-out)*250}px) rotate(${i?9:-9}deg)`});for(const el of story.querySelectorAll('[data-cinema-copy]')){const second=el.dataset.cinemaCopy==='2';const a=second?ease(clamp((p-.35)/.15))*(1-ease(clamp((p-.64)/.12))):ease(clamp((p-.76)/.14));el.style.opacity=a;el.style.visibility=a<.01?'hidden':'visible';el.inert=a<.5;el.style.transform=mobile.matches?`translateY(${20*(1-a)}px)`:`translateY(calc(-50% + ${30*(1-a)}px))`;el.style.top=mobile.matches?'7%':'50%'}story.querySelector('.cinema-progress i').style.transform=`scaleX(${p})`;const chapter=p<.15?0:p<.4?1:p<.78?2:3;pin.dataset.chapter=chapter;pin.dataset.progress=p.toFixed(4);document.querySelector('#cinema-label').textContent=['SCROLL TO EXPLORE THE POSSIBILITIES','01 / A WORLD OF YOUR OWN','02 / A CLEARER POINT OF VIEW','03 / DESIGNED FOR EVERY SCREEN'][chapter];}
function schedule(){if(!frame)frame=requestAnimationFrame(draw)}
function mode(){nav.cancel();enabled=!reduced.matches;story.classList.toggle('motion-enabled',enabled);story.classList.toggle('cinema-reading',!enabled);if(!enabled){[site,intro,...story.querySelectorAll('.cinema-side,.cinema-caption')].forEach(e=>{e.removeAttribute('style');e.inert=false});}measure()}
document.querySelector('#cinema-next').addEventListener('click',()=>{if(!nav.step(1))document.querySelector('.image-range').scrollIntoView({behavior:'smooth'})});document.querySelector('#cinema-back').addEventListener('click',()=>nav.step(-1));
window.addEventListener('wheel',event=>{if(event.ctrlKey||Math.abs(event.deltaX)>Math.abs(event.deltaY)||event.target.closest('input,textarea,select'))return;if(nav.wheel(event.deltaY*(event.deltaMode===1?16:1)))event.preventDefault()},{passive:false});let touchY=null,touchConsumed=false;story.addEventListener('touchstart',e=>{touchConsumed=false;touchY=e.touches.length===1?e.touches[0].clientY:null},{passive:true});story.addEventListener('touchmove',e=>{if(touchConsumed){if(nav.running)e.preventDefault();return}if(touchY===null||e.touches.length!==1||e.target.closest('a,button,input'))return;const delta=touchY-e.touches[0].clientY;if(Math.abs(delta)>22&&nav.canStep(Math.sign(delta))){e.preventDefault();nav.step(Math.sign(delta));touchConsumed=true;}},{passive:false});story.addEventListener('touchend',()=>{touchY=null},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.cancel();return}if(e.target.closest('input,textarea,select,button,a'))return;if(['ArrowDown','ArrowUp','PageDown','PageUp'].includes(e.key)&&nav.step(['ArrowDown','PageDown'].includes(e.key)?1:-1))e.preventDefault()});addEventListener('scroll',schedule,{passive:true});addEventListener('resize',measure,{passive:true});reduced.addEventListener('change',mode);document.querySelectorAll('.cinema-caption h2 br').forEach(br=>br.after(document.createTextNode(' ')));mode();
