(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const features={architecture:{brand:'ARC / HOUSE',title:'A quieter kind\nof extraordinary.',image:'assets/arc-coast-process.webp',category:'RESIDENTIAL ARCHITECTURE',caption:'Considered homes. A deeper connection to place.',nav:'Residences   Practice   Inquire ↗',bottom:'01 / THE COASTAL HOUSE',url:'demo-architecture.html',alt:'Coastal residence in the ARC House architecture design study'},wellness:{brand:'FORM / 01',title:'Move well.\nFeel more.',image:'assets/form-01.webp',category:'A DIFFERENT KIND OF MOVEMENT STUDIO',caption:'Find a little strength. Make a little space.',nav:'Method   Classes   Join ↗',bottom:'02 / FIND YOUR MOVEMENT',url:'demo-wellness.html',alt:'Reformer movement in the FORM 01 wellness design study'},industrial:{brand:'FORGE /// SYSTEMS',title:'Less guesswork.\nA clearer signal.',image:'assets/forge-systems.webp',category:'INDUSTRIAL INTELLIGENCE',caption:'Understand the issue. Know your next move.',nav:'Platform   Decision record   Study ↗',bottom:'03 / FROM SIGNAL TO DECISION',url:'demo-industrial.html',alt:'Industrial equipment in the Forge Systems design study'}};
const demo=document.querySelector('.r-demo');let request=0;
function reveal(){if(!demo||reduced)return;demo.classList.remove('is-revealing');requestAnimationFrame(()=>requestAnimationFrame(()=>demo.classList.add('is-revealing')))}
document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',async()=>{const id=++request;const f=features[b.dataset.feature];const img=new Image();img.src=f.image;try{await img.decode()}catch{return}if(id!==request)return;demo.dataset.kind=b.dataset.feature;document.querySelector('#feature-image').src=f.image;document.querySelector('#feature-image').alt=f.alt;for(const key of ['brand','category','caption','nav','bottom'])document.querySelector('#feature-'+key).textContent=f[key];const title=document.querySelector('#feature-title');title.replaceChildren(...f.title.split('\n').flatMap((s,i)=>i?[document.createElement('br'),document.createTextNode(s)]:[document.createTextNode(s)]));document.querySelector('#feature-link').href=f.url;document.querySelectorAll('[data-feature]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));reveal()}));
document.querySelector('#replay-build')?.addEventListener('click',reveal);
document.querySelector('#quick-start')?.addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#current-website-url');input.value=document.querySelector('#quick-url').value.trim();const mode=document.querySelector('#project-mode');mode.value='existing';mode.dispatchEvent(new Event('change'));document.querySelector('#studio').scrollIntoView({behavior:reduced?'auto':'smooth'});input.focus({preventScroll:true})});
document.querySelector('#start-new')?.addEventListener('click',()=>{const mode=document.querySelector('#project-mode');mode.value='new';mode.dispatchEvent(new Event('change'))});
document.querySelector('#vision-custom-headline')?.addEventListener('input',event=>{document.querySelector('#vision-headline').textContent=event.target.value.trim()||'Your next chapter starts here.'});
document.querySelector('#vision-accent')?.addEventListener('input',event=>{const color=event.target.value;document.querySelector('.vision-canvas').style.setProperty('--concept-accent',color);const rgb=color.slice(1).match(/../g).map(x=>parseInt(x,16));document.querySelector('.vision-message>a').style.color=(rgb[0]*.299+rgb[1]*.587+rgb[2]*.114)>150?'#182010':'#ffffff'});
const plan=new URLSearchParams(location.search).get('plan');const plans={launch:'Launch · $500 · One page',business:'Business · $1,000 · Up to five pages',premium:'Premium · $1,500 · Up to eight pages'};const selection=document.querySelector('#selected-plan');if(selection&&plans[plan]){selection.hidden=false;selection.textContent='Your starting package: '+plans[plan]+'. Final scope confirmed before payment.';const notes=document.querySelector('#order-notes');if(notes)notes.value='Package preference: '+plans[plan]+'\n';}
document.querySelectorAll('#main-navigation>a').forEach(a=>{if(a.getAttribute('href')===location.pathname.split('/').pop())a.setAttribute('aria-current','page')});
})();

document.querySelectorAll('[data-concept-style]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.vision-browser').dataset.visionTheme=button.dataset.conceptStyle;document.querySelectorAll('[data-concept-style]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))}));
