import {createSceneNavigator,RESTS} from './motion-lab/navigation.mjs';
import './story-directions.mjs?v=6';
const story=document.querySelector('.s-story'),stage=story.querySelector('.s-stage'),site=story.querySelector('.s-web');
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width:760px)');
const clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>x*x*(3-2*x);let m={},frame=0,enabled=false;
const phone=document.createElement('article');phone.className='s-web s-phone-site';phone.setAttribute('aria-label','Phone composition of the selected design');stage.append(phone);
function syncPhone(){phone.innerHTML=site.innerHTML;phone.dataset.brand=site.dataset.brand||'field';phone.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));phone.querySelector('.s-blueprint')?.remove();phone.querySelectorAll('[style]').forEach(e=>e.removeAttribute('style'));}
syncPhone();document.addEventListener('story-direction-change',()=>{syncPhone();stage.querySelector('.story-atmosphere img').src=site.querySelector('.s-web-photo').src;});
const blueprint=site.querySelector('.s-blueprint');site.querySelector('.s-web-page').append(blueprint);
const progress=()=>clamp((scrollY-m.top)/m.travel);
function measure(){m={top:story.getBoundingClientRect().top+scrollY-document.querySelector('.site-header').offsetHeight,travel:Math.max(1,story.offsetHeight-stage.offsetHeight),w:stage.clientWidth,h:stage.clientHeight};schedule()}
const nav=createSceneNavigator({getProgress:progress,seek:p=>{scrollTo({top:m.top+p*m.travel,behavior:'instant'});schedule()},isEnabled:()=>enabled&&scrollY>=m.top-2&&scrollY<=m.top+m.travel+2,now:()=>performance.now(),requestFrame:requestAnimationFrame,cancelFrame:cancelAnimationFrame});
function fit(box,width=mobile.matches?360:1100,height=mobile.matches?620:740){const scale=Math.min(box[2]*m.w/width,box[3]*m.h/height);return [box[0]*m.w+(box[2]*m.w-width*scale)/2,box[1]*m.h+(box[3]*m.h-height*scale)/2,scale]}
function draw(){frame=0;if(!enabled)return;const p=progress(),small=mobile.matches;const opening=stage.querySelector(".product-opening"),openingOut=1-ease(clamp((p-.01)/.1));opening.style.opacity=openingOut;opening.style.transform=`translateY(${-40*(1-openingOut)}px)`;opening.style.visibility=openingOut<.01?"hidden":"visible";opening.inert=openingOut<.5;const boxes=small?[[.08,.44,.84,.44],[.04,.46,.92,.43],[0,.075,1,.83],[.02,.36,.5,.30]]:[[.48,.16,.49,.71],[.48,.10,.50,.82],[0,.015,1,.83],[.33,.28,.31,.43]];let n=RESTS.findIndex((x,i)=>i<3&&p>=x&&p<=RESTS[i+1]);if(n<0)n=2;const t=ease(clamp((p-RESTS[n])/(RESTS[n+1]-RESTS[n]))),from=fit(boxes[n]),to=fit(boxes[n+1]),r=from.map((x,i)=>x+(to[i]-x)*t);const targetPhone=fit(small?[.13,.36,.74,.57]:[.62,.075,.30,.84],360,690);if(n===2){const target=[targetPhone[0],targetPhone[1],targetPhone[2]*360/(small?360:1100)];for(let k=0;k<3;k++)r[k]=from[k]+(target[k]-from[k])*t;}site.style.transform=`translate3d(${r[0]}px,${r[1]}px,0) scale(${r[2]})`;
 const atmosphere=stage.querySelector('.story-atmosphere');atmosphere.style.opacity=ease(clamp((p-.32)/.2));atmosphere.style.transform=`scale(${1.08-.08*ease(clamp((p-.32)/.68))})`;stage.classList.toggle('story-immersed',p>.40);const phoneIn=ease(clamp((p-.76)/.19));site.style.opacity=1-phoneIn;site.inert=phoneIn>.8;site.style.visibility=phoneIn>.999?'hidden':'visible';const pr=fit(small?[.13,.36,.74,.57]:[.62,.075,.30,.84],360,690);phone.style.transform=`translate3d(${r[0]}px,${r[1]}px,0) scale(${r[2]*(small?360:1100)/360})`;phone.style.opacity=phoneIn;phone.style.visibility=phoneIn<.001?'hidden':'visible';phone.inert=phoneIn<.8;
 const out=1-ease(clamp(p/.19));story.querySelectorAll('.s-floating').forEach((el,i)=>{el.style.opacity=out;el.style.transform=`translate3d(${(i?1:-1)*(1-out)*400}px,${-35*(1-out)}px,0) rotate(${(i?8:-9)*out}deg)`});
 for(const el of story.querySelectorAll('[data-story-copy]')){const id=Number(el.dataset.storyCopy);const a=id===1?ease(clamp((p-.12)/.1))*(1-ease(clamp((p-.29)/.09))):id===3?ease(clamp((p-.82)/.16)):0;el.style.opacity=a;el.style.visibility=a<.01?'hidden':'visible';el.inert=a<.5;el.style.transform=`translateY(${28*(1-a)}px)`}
 const assembly=p>.24?ease(clamp((p-.29)/.23)):1,bp=ease(clamp((p-.09)/.1))*(1-ease(clamp((p-.30)/.10)));blueprint.style.opacity=bp;site.querySelector('.s-web-photo').style.clipPath=p>.24&&p<.56?`inset(0 ${100*(1-assembly)}% 0 0)`:'none';site.querySelector('.s-web-photo').style.transform=`scale(${1.08-.08*assembly})`;const copy=site.querySelector('.s-web-copy');copy.style.opacity=1-bp;copy.style.transform=`translateY(${(1-assembly)*30}px)`;site.querySelector('.s-web-lower').style.transform=`translateY(${(1-assembly)*45}px)`;const building=p>.24&&p<.56;copy.querySelectorAll('small,h2,p,a').forEach((el,i)=>{const reveal=building?ease(clamp((p-(.32+i*.035))/.075)):1;el.style.opacity=reveal;el.style.transform=`translateY(${(1-reveal)*24}px)`});const lower=site.querySelector('.s-web-lower');lower.style.opacity=building?ease(clamp((p-.46)/.09)):1;
 const chooser=story.querySelector('.story-directions'),choices=p>.43&&p<.70;chooser.style.visibility=choices?'visible':'hidden';chooser.style.opacity=choices?'1':'0';chooser.inert=!choices;story.querySelector('.s-story-progress i').style.transform=`scaleX(${p})`;const chapter=p<.12?0:p<.38?1:p<.77?2:3;stage.dataset.chapter=chapter;stage.dataset.progress=p.toFixed(4);document.querySelector('#story-counter').textContent=['01 / POSSIBILITY','02 / THE IDEA','03 / THE EXPRESSION','04 / EVERY SCREEN'][chapter];}
function schedule(){if(!frame)frame=requestAnimationFrame(draw)}
function mode(){nav.cancel();enabled=!reduced.matches;story.classList.toggle('s-reading',!enabled);if(!enabled){stage.classList.remove('story-immersed');stage.querySelector('.story-atmosphere').removeAttribute('style');stage.querySelector(".product-opening").removeAttribute("style");stage.querySelector(".product-opening").inert=false;[site,phone,...story.querySelectorAll('.s-floating,.s-story-copy,.s-web-photo,.s-web-copy,.s-web-copy small,.s-web-copy h2,.s-web-copy p,.s-web-copy a,.s-blueprint,.s-web-lower,.story-directions')].forEach(e=>{e.removeAttribute('style');e.inert=false})}measure()}
document.querySelector('#story-next').addEventListener('click',()=>{if(scrollY<m.top){scrollTo({top:m.top,behavior:'instant'});nav.step(1)}else if(!nav.step(1))document.querySelector('#studio').scrollIntoView({behavior:reduced.matches?'auto':'smooth'})});document.querySelector('#story-back').addEventListener('click',()=>nav.step(-1));
addEventListener('wheel',e=>{if(e.ctrlKey||Math.abs(e.deltaX)>Math.abs(e.deltaY)||e.target.closest('input,textarea,select'))return;if(nav.wheel(e.deltaY*(e.deltaMode===1?16:1)))e.preventDefault()},{passive:false});let touchY=null,consumed=false;story.addEventListener('touchstart',e=>{consumed=false;touchY=e.touches.length===1?e.touches[0].clientY:null},{passive:true});story.addEventListener('touchmove',e=>{if(consumed){if(nav.running)e.preventDefault();return}if(touchY===null||e.touches.length!==1||e.target.closest('a,button,input'))return;const delta=touchY-e.touches[0].clientY;if(Math.abs(delta)>22&&nav.canStep(Math.sign(delta))){e.preventDefault();nav.step(Math.sign(delta));consumed=true}},{passive:false});story.addEventListener('touchend',()=>touchY=null,{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.cancel();return}if(e.target.closest('input,textarea,select,button,a'))return;if(['ArrowDown','ArrowUp','PageDown','PageUp'].includes(e.key)&&nav.step(['ArrowDown','PageDown'].includes(e.key)?1:-1))e.preventDefault()});addEventListener('scroll',schedule,{passive:true});addEventListener('resize',measure,{passive:true});reduced.addEventListener('change',mode);mode();
