import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const project = join(dirname(fileURLToPath(import.meta.url)), '..');
const root = existsSync(join(project,'dist','index.html')) ? join(project,'dist') : project;
const mark = '<span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>';
const link = (page,href,label,extra='') => `<a href="${href}"${page===href?' aria-current="page"':''}${extra}>${label}</a>`;
function header(page){return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html" aria-label="Website Builder home">${mark}<span>Website Builder</span></a><button class="mobile-menu-button" aria-expanded="false" aria-controls="main-navigation">Menu <span aria-hidden="true">☰</span></button><nav id="main-navigation" aria-label="Main navigation"><details class="nav-group"><summary>Website <span aria-hidden="true">⌄</span></summary><div class="nav-popover"><p>Explore the experience</p>${link(page,'how-it-works.html','<b>How it works</b><small>From a brief to a website you own</small>')}${link(page,'examples.html','<b>Design examples</b><small>Different businesses. Different worlds.</small>')}${link(page,'quality.html','<b>Our quality standard</b><small>What a complete build should pass</small>')}</div></details><details class="nav-group"><summary>Resources <span aria-hidden="true">⌄</span></summary><div class="nav-popover resources-popover"><p>Make a better website decision</p>${link(page,'premium-website-value.html','<b>Why design matters</b><small>Where quality creates business value</small>')}${link(page,'seo-website-design.html','<b>Search-ready foundations</b><small>What SEO included should mean</small>')}${link(page,'custom-website-vs-ai-builder.html','<b>Beyond a single AI prompt</b><small>DIY and managed design, compared</small>')}${link(page,'website-redesign-guide.html','<b>When to redesign</b><small>Diagnose before you rebuild</small>')}${link(page,'resources.html','View all resources →',' class="nav-all"')}</div></details>${link(page,'pricing.html','Pricing')}${link(page,'about.html','About')}<a class="nav-cta" href="index.html#studio">Try the prototype <span aria-hidden="true">↗</span></a></nav></header>`;}
const footer=`<footer class="site-footer"><div class="footer-main"><div class="footer-brand"><a class="brand" href="index.html">${mark}<span>Website Builder</span></a><p>A considered website.<br>A clearer way to get there.</p><span>Product prototype by Stromation</span></div><div><h2>Explore</h2><a href="how-it-works.html">How it works</a><a href="examples.html">Design examples</a><a href="pricing.html">Pricing</a><a href="quality.html">Quality standard</a></div><div><h2>Learn</h2><a href="premium-website-value.html">Why design matters</a><a href="seo-website-design.html">SEO foundations</a><a href="custom-website-vs-ai-builder.html">AI vs managed design</a><a href="website-redesign-guide.html">Redesign guide</a></div><div><h2>Company</h2><a href="about.html">Our story</a><a href="faq.html">Questions & answers</a><a href="resources.html">All resources</a><a href="feed.xml">RSS feed</a></div></div><div class="footer-bottom"><span>© 2026 Stromation. Temporary product name.</span><span>Demonstration only. No payments or live generation.</span></div></footer>`;
for(const name of readdirSync(root).filter(x=>x.endsWith('.html')&&!x.startsWith('demo-'))){
 const p=join(root,name);let html=readFileSync(p,'utf8');
 html=html.replace(/<body(?: class="([^"]*)")?>/,(_match,classes='')=>`<body class="${[...new Set(['premium-site',...classes.split(/\s+/).filter(Boolean)])].join(' ')}">`);
 html=html.replace(/(?:<a class="skip-link"[^]*?<\/a>)?<header class="(?:topbar|site-header)"[^]*?<\/header>/,header(name));
 html=html.replace(/<main(?: id="[^"]*")?/, '<main id="main"');
 html=html.replace(/<footer(?: class="site-footer")?><div>(?:(?!<\/footer>)[^])*<\/footer>/,footer);
 if(html.includes('<footer class="site-footer">'))html=html.replace(/<footer class="site-footer">[^]*?<\/footer>/,footer);
 if(!html.includes('href="premium.css"'))html=html.replace('</head>','<link rel="stylesheet" href="premium.css"></head>');
 if(!html.includes('src="site.js"'))html=html.replace('</body>','<script src="site.js" defer></script></body>');
 writeFileSync(p,html);
}
console.log('Shared navigation and footer synchronized.');
