import {directions} from './model.mjs';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function conceptHTML(id,version=0){
 const d=directions.find(x=>x.id===id)||directions[0];
 const full=version>=2;
 const intro=version>=3?'A clearer story. A more confident next step.':d.headline;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Northline Studio — ${d.name} sample</title><style>
 *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fafafa;color:#1c273d;font:17px/1.6 Arial,sans-serif}a{color:inherit;text-underline-offset:5px}nav{display:flex;justify-content:space-between;align-items:center;padding:25px 6vw;border-bottom:1px solid #bcc4d166;font-size:14px}nav b{font-size:19px}nav div{display:flex;gap:22px}section{padding:70px 6vw}h1{font-size:clamp(48px,7vw,100px);line-height:1.02;letter-spacing:-.065em;margin:20px 0 28px;max-width:900px}h2{font-size:clamp(30px,4vw,50px);line-height:1.12;letter-spacing:-.04em}p{max-width:590px}small{font-size:12px;text-transform:uppercase;letter-spacing:.12em}.cta{display:inline-block;background:#283cc8;color:#fff;padding:15px 24px;border-radius:5px;text-decoration:none;margin-top:20px}.hero{min-height:560px;display:grid;grid-template-columns:1.5fr .6fr;align-items:end;gap:50px}.index{font-size:14px;border-top:1px solid;padding-top:20px}.services{display:grid;grid-template-columns:repeat(3,1fr);gap:35px;margin-top:40px}.services article{border-top:1px solid;padding-top:20px}footer{padding:25px 6vw;font-size:12px;background:#eef0f5}.current{background:#d8ef3e;color:#183728}.current nav{border-color:#183728}.current .hero{display:block;min-height:620px}.current h1{font-size:clamp(64px,10vw,140px);max-width:1050px}.current .index{display:flex;justify-content:space-between;gap:35px;margin-top:45px}.current .cta{background:#183728;color:#e2f680;border-radius:40px}.current .service-section{background:#183728;color:#e5f5a2}.ledger{background:#f7f3ec;color:#343c35;font-family:Georgia,serif}.ledger nav{font-family:Arial,sans-serif}.ledger .hero{display:grid;grid-template-columns:140px 1fr;align-items:start}.ledger h1{font-weight:400;letter-spacing:-.04em;font-size:clamp(45px,6vw,88px)}.ledger .hero>div{grid-column:2}.ledger .hero .index{grid-column:1;grid-row:1;border:0;font-size:13px;font-family:Arial,sans-serif}.ledger .cta{background:transparent;color:inherit;border:1px solid;border-radius:0}.ledger .services{grid-template-columns:1fr}.ledger .services article{display:grid;grid-template-columns:1fr 2fr;gap:30px}.ledger h2{font-weight:400}.contact{border-top:1px solid #abb3a966}.sample-note{font-size:13px;padding:10px 6vw;background:#19243b;color:white}a:focus-visible{outline:3px solid #dd7534;outline-offset:5px}@media(max-width:600px){nav{padding:20px}nav div{gap:12px}section{padding:45px 22px}.hero,.ledger .hero{display:block;min-height:0}.hero .index{margin-top:35px}.services,.ledger .services article{display:block}.services article{margin:30px 0}.current .hero{min-height:0}.current .index{display:block}.current h1{font-size:65px}.ledger h1{font-size:49px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
 </style></head><body class="${d.id}"><div class="sample-note">Fictional business · ${full?'Complete sample':'Concept study'} · ${d.name}</div><nav><b>NORTHLINE${d.id==='current'?'®':' / STUDIO'}</b><div><a href="#approach">Approach</a><a href="#contact">Contact ↗</a></div></nav><section class="hero"><div><small>Positioning / Messaging / Brand strategy</small><h1>${intro}</h1><p>We help founders of growing service businesses explain what makes them different — and give their next chapter a clear direction.</p><a class="cta" href="#contact">Request a consultation ↗</a></div><aside class="index">Independent strategy.<br>Thoughtful collaboration.<br>A story that sounds like you.</aside></section><section id="approach" class="service-section"><small>01 / Our approach</small><h2>Start with the business.<br>Find the words that fit.</h2><p>We work with you to clarify your audience, articulate your offer and build a shared foundation for how your business communicates.</p>${full?'<div class="services"><article><h3>Positioning</h3><p>Define who you serve, the problems you solve and why your approach matters.</p></article><article><h3>Messaging</h3><p>Turn strategic thinking into a clear story, practical language and a useful message hierarchy.</p></article><article><h3>Brand strategy</h3><p>Give your team principles they can use to make consistent choices as the business grows.</p></article></div>':'<p><em>Concept study: the complete service section follows direction approval.</em></p>'}</section>${full?'<section><small>02 / Working together</small><h2>A conversation.<br>A shared direction.<br>A useful foundation.</h2><p>We start by listening. Together, we explore the business, shape its positioning and refine the language until it is clear enough to use.</p></section>':''}<section id="contact" class="contact"><small>Let’s find your next step</small><h2>Tell us what’s changing.</h2><p>Sample consultation destination. Contact details will come from the approved business brief.</p></section><footer>Northline Studio is fictional. Prepared to demonstrate a customer’s design review; no client results or live contact form.</footer></body></html>`;
}
