import {mountLiveProject} from './live.mjs?v=livecanvas1';
import {saveSession,loadSession,consumeSessionFragment,clearSession} from './session.mjs';
import {stages,directions,fresh,transition} from './model.mjs';
import {conceptHTML,escapeHTML as e} from './concepts.mjs';
import {loadProjects,saveProject} from './storage.mjs';
import {normalizeWebsiteURL,validateBrief,briefPayload} from './intake.mjs';
const $=s=>document.querySelector(s), key='website-builder-workspace-v1';
let state=fresh(),view=0,previewDirection=null,previewVersion=null,busy=false,storageOK=true;
let projects={schema:2,active:'real',real:fresh(),sample:fresh(true)};
try{projects=loadProjects(localStorage,key);state=projects[projects.active]||projects.real;}catch{storageOK=false;}
view=state.stage;
let liveSession=consumeSessionFragment()||loadSession(),liveCleanup;
function save(){try{saveProject(localStorage,key,projects,state);storageOK=true;}catch{storageOK=false;}$('#save-state').textContent=storageOK?'Saved on this device':'Storage unavailable — keep this tab open';}
function act(event){try{state=transition(state,event);view=state.stage;save();render();$('#main').focus();}catch(error){notice(error.message);}}
function notice(message){$('#notice').textContent=message;}
const intro=(kicker,title,body)=>`<header class="intro"><p class="overline">${kicker}</p><h2>${title}</h2><p>${body}</p></header>`;
const field=(name,label,placeholder='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${e(state.brief[name])}" placeholder="${placeholder}" maxlength="500" ${state.sample?'readonly':''} ${['domain','contact_email'].includes(name)?'':'required'}></label>`;
function briefSummary(includeBusiness=false){
 const existing=state.brief.project_mode==='existing';
 const labels=existing?{current_website_url:'Current website',domain:'Website domain',change_notes:'What should work better',keep_notes:'What to keep'}:{...(includeBusiness?{business_name:'Business'}:{}),buyer:'Audience',offer:'Offer',primary_action:'Visitor action',reference_notes:'Preferences'};
 return `<div class="summary-row"><dt>Project</dt><dd>${existing?'Improve an existing website':'Create a new website'}</dd></div>`+Object.entries(labels).map(([k,v])=>`<div class="summary-row"><dt>${v}</dt><dd>${e(state.brief[k]||'Not specified')}</dd></div>`).join('');
}
function projectFields(){
 const existing=state.brief.project_mode==='existing';
 return `<label>What would you like to do?<select name="project_mode" ${state.sample?'disabled':''}><option value="existing" ${existing?'selected':''}>Improve an existing website</option><option value="new" ${!existing?'selected':''}>Create a new website</option></select></label>${existing?`<div class="redesign-fields"><label>Current website URL<input name="current_website_url" value="${e(state.brief.current_website_url)}" placeholder="https://yourbusiness.com" maxlength="1000" required inputmode="url" autocomplete="url"></label><label>What should work better?<textarea name="change_notes" required minlength="10" maxlength="4000" rows="3" placeholder="Help visitors book on mobile, explain our services more clearly, make the site feel more like us…">${e(state.brief.change_notes)}</textarea></label><label>Anything we should keep? <span class="helper">(optional)</span><textarea name="keep_notes" maxlength="4000" rows="3" placeholder="Our logo, useful pages, colors or features people already like…">${e(state.brief.keep_notes)}</textarea></label><p class="helper">We’ll review the website for context and confirm anything unclear. We haven’t inspected it yet.</p></div>`:''}`;
}
function brief(){
 if(state.stage>0)return intro('01 / Your foundation','Your confirmed brief.','Your website and priorities stay visible throughout the project.')+`<div class="paper"><dl>${briefSummary(true)}</dl><button data-view="${state.stage}" class="primary">Return to current step →</button></div>`;
 const existing=state.brief.project_mode==='existing';
 const questions=existing?'':`${field('business_name','Business name','Your business')}${field('offer','What do you offer?','The service or product people come to you for')}${field('buyer','Who are you trying to reach?','The people who should choose you')}${field('primary_action','What should a visitor do?','Book a consultation, request a quote…')}<label>References, personality and things to avoid<textarea name="reference_notes" ${state.sample?'readonly':''} required maxlength="4000" rows="4">${e(state.brief.reference_notes)}</textarea></label>`;
 return intro('01 / Your foundation',existing?'Let’s improve what you already have.':'Let’s get to know your business.',existing?'Share your website and the main thing you want to improve. You’ll review everything before sending.':'A few specifics give the design a direction. You’ll review the brief before sending anything.')+`<div class="brief-layout"><form id="brief-form" class="paper">${projectFields()}${questions}<button class="primary" type="submit">Review my brief →</button></form><aside><h3>${existing?'Start with what matters.':'A website that feels like you.'}</h3><p class="muted">${existing?'Your website provides the starting context. Tell us the outcome you want, and anything important to preserve.':'Your audience and offer guide the structure. Your references help set the personality.'}</p><div class="callout"><h3>You make the key decisions.</h3><p>Choose a design direction before the full build. Review the finished website before launch.</p></div><p class="helper">${state.sample?'Northline Studio is a fictional strategy business. Its three prepared concepts let you test the full decision flow.':'This draft stays in your browser. Confirming it here does not start or pay for a build.'}</p></aside></div>`;
}
function research(){return intro('02 / Research',state.sample?'Your brief, translated into a direction.':state.receipt?'Your brief is in scope review.':'Review your brief before we begin.',state.sample?'These are prepared interpretations of the fictional brief, not findings from live research.':state.receipt?'A brief receipt is the first step. Research and design updates will appear here once the project service is connected.':'Check the facts, then send your brief for a scope and price review.')+`<div class="two-column"><div class="paper"><h3>${e(state.brief.project_mode==='existing'?state.brief.domain:state.brief.business_name)}</h3><dl>${briefSummary()}</dl>${state.sample?'<div class="callout"><b>Design implication</b><p>Make the strategy service concrete, keep the consultation easy to find, and demonstrate judgment through clear writing.</p><span class="tag">Source: sample business brief</span></div>':state.receipt?`<p class="tag">Receipt: ${e(state.receipt)}</p><p class="helper">Nothing has been charged and no build has started.</p>`:`<form id="send-form"><div class="fields">${state.brief.project_mode==='existing'?'':field('domain','Your domain','yourbusiness.com')}${field('contact_email','Where should we reply?','you@business.com','email')}</div><p class="helper">Sending records your brief with the Website Builder team for scope review. Nothing is charged and no build starts.</p><button class="primary" type="submit">Send brief for scope review →</button></form>`}</div><aside><h3>${state.sample?'What we would validate':'What happens next'}</h3><ul class="check-list"><li>Business facts and available proof</li><li>Buyer needs and category expectations</li><li>Competitor and reference review</li><li>Three distinct design arguments</li></ul><p class="helper">${state.sample?'No competitor research has been performed for this sample. Use the sample milestone control to see the prepared choices.':'This preview currently accepts briefs. Live project tracking and customer approvals still need the Sol connection.'}</p>${!state.receipt&&!state.sample?'<button id="edit-brief">Edit brief</button>':''}</aside></div>`;}
function preview(id,version){return `<div class="preview-shell"><div class="preview-toolbar"><b>${e(directions.find(d=>d.id===id)?.name)} · ${version?`Version ${version}`:'Concept study'}</b><div><button data-device="desktop" aria-pressed="true">Desktop</button><button data-device="mobile" aria-pressed="false">Mobile</button></div></div><div class="preview-window desktop"><iframe title="Northline website preview" sandbox="" data-concept="${id}" data-version="${version}"></iframe></div></div>`;}
function choices(){const selected=previewDirection||state.selected;return intro('03 / Your first decision','Same business. Three different directions.','Explore the actual layouts. Choose the one that feels right, then tell us what you’d refine.')+`<div class="directions">${directions.map(d=>`<article class="direction ${selected===d.id?'selected':''}"><div class="thumb" inert aria-hidden="true"><iframe title="${d.name} concept thumbnail" sandbox="" tabindex="-1" loading="lazy" data-concept="${d.id}" data-version="0"></iframe></div><div class="direction-content"><span class="tag">${d.voice}</span><h3>${d.name}</h3><p>${d.description}</p><p>${d.tradeoff}</p><button data-inspect="${d.id}" aria-pressed="${selected===d.id}">Explore ${d.name} ↗</button></div></article>`).join('')}</div>${selected?`<div class="choice-detail">${preview(selected,0)}${state.stage===2?`<form id="direction-form" class="paper"><h3>Continue with ${e(directions.find(d=>d.id===selected).name)}?</h3><label>What should we keep or refine?<textarea name="note" maxlength="4000" placeholder="For example: keep the typography, make the opening more direct…">${e(state.directionNote)}</textarea></label><p class="helper">Sample feedback is saved for this walkthrough. It is not sent to a designer or interpreted by Sol.</p><button class="primary" type="submit">Confirm this direction →</button></form>`:`<p class="helper">Approved direction: ${e(directions.find(d=>d.id===state.selected)?.name)}. Exploring another concept does not change your selection.</p>`}</div>`:''}`;}
function build(){const version=previewVersion||state.versions.at(-1)?.id;return intro('04 / Taking shape','Your direction becomes a website.',state.versions.length?'Review the available preview while the next milestone is prepared.':'The direction is confirmed. The first milestone is a working homepage proof.')+`<div class="two-column"><div class="paper"><span class="tag">${e(directions.find(d=>d.id===state.selected)?.name)} · Confirmed</span><ul class="check-list"><li class="done">Business brief confirmed</li><li class="done">Design direction selected</li><li class="${state.versions.length?'done':''}">Homepage proof</li><li class="${state.versions.length>=2?'done':''}">Complete sample website</li><li>Final customer approval</li></ul>${state.directionNote?`<h3>Your direction notes</h3><p>${e(state.directionNote)}</p>`:''}${state.feedback.length?`<h3>Latest revision request</h3><p>${e(state.feedback.at(-1).note)}</p><p class="helper">The next sample milestone loads a prepared copy variation to demonstrate revision review. It does not fulfill your request.</p>`:''}</div><aside><h3>Project activity</h3>${activity()}</aside></div>${version?versions()+preview(state.selected,version):'<div class="callout"><h3>Waiting for the first preview</h3><p>No estimated percentage or simulated loading timer. A preview appears when a recorded milestone is available.</p></div>'}`;}
function versions(){return `<div class="actions" style="margin-top:24px">${state.versions.map(v=>`<button data-version-choice="${v.id}">V${v.id} · ${e(v.label)}</button>`).join('')}</div>`;}
function review(){return intro('05 / Your review','Walk through it. Make it yours.','Check the full page on desktop and mobile, then request changes or approve the sample handoff.')+versions()+preview(state.selected,previewVersion||state.versions.at(-1).id)+(state.stage===5?'<p class="helper">This sample version has already been approved.</p><button data-view="5" class="primary">Return to handoff →</button>':`<div class="two-column"><form id="feedback-form" class="paper"><h3>What should change?</h3><label>Section<select name="section"><option>Opening</option><option>Approach and services</option><option>Contact</option><option>Mobile layout</option><option>Whole website</option></select></label><label>Your feedback<textarea name="note" required maxlength="4000" placeholder="Describe the change and why it matters…"></textarea></label><button type="submit">Save sample revision request →</button>${state.feedback.map(f=>`<div class="feedback-item"><b>${e(f.section)} · V${f.version}</b><p>${e(f.note)}</p></div>`).join('')}</form><form id="approval-form" class="paper"><h3>Ready for handoff?</h3><p>In a live project, this is the decision that releases the approved version for launch.</p><label class="approval-check"><input name="approved" type="checkbox" required><span>I’ve reviewed the latest sample version and want to approve its handoff.</span></label><p class="helper">This is a sample approval. It publishes nothing and changes no domain.</p><button class="primary" type="submit">Approve sample handoff →</button></form></div>`);}
function handoff(){return intro('06 / Handoff','Your decision is recorded.','You’ve completed the sample customer journey, from business brief to design selection and final approval.')+`<div class="two-column"><div class="paper"><span class="tag">Sample approval · Nothing published</span><h3 style="margin-top:24px">${e(state.brief.business_name)}</h3><p>${e(directions.find(d=>d.id===state.selected)?.name)} · Version ${state.versions.at(-1).id}</p><div class="actions"><button id="download-site" class="primary">Download sample website</button><button id="download-record">Download project record</button></div><div class="callout"><h3>For a live launch</h3><p>The approved version, domain connection, deployment checks and source package must come from the project service. Those are not connected in this preview.</p></div><button data-view="4">Revisit your review</button></div><aside><h3>The decisions along the way</h3>${activity()}</aside></div>`;}
function activity(){return `<ol class="timeline">${state.events.slice().reverse().map(x=>`<li><small>${e(new Date(x.at).toLocaleString())}</small>${e(x.message)}</li>`).join('')}</ol>`;}
const thumbnailObserver=new ResizeObserver(entries=>entries.forEach(({target,contentRect})=>{target.querySelector('iframe').style.transform=`scale(${contentRect.width/1000})`;}));
function render(){
 liveCleanup?.();liveCleanup=null;
 if(!state.sample&&liveSession){
  $('#mode-label').textContent='Your live project';$('#sample-toggle').textContent='Explore sample project';
  $('#project-name').textContent='Your website';$('#project-state').textContent='Connected to project updates';
  $('#stages').innerHTML='';$('#sample-controls').hidden=true;$('#surface').innerHTML='';
  liveCleanup=mountLiveProject($('#surface'),liveSession);return;
 }

 $('#project-name').textContent=(state.brief.project_mode==='existing'?state.brief.domain||state.brief.current_website_url:state.brief.business_name)||'A new beginning.';$('#project-state').textContent=stages[state.stage]+(state.stage===2?' · Your decision':state.stage===1&&!state.sample?' · Awaiting scope review':'');
 $('#mode-label').textContent=state.sample?'Sample project · Saved on this browser':'Your project draft · Saved on this browser';$('#sample-toggle').textContent=state.sample?'Return to my project':'Explore sample project';
 $('#stages').innerHTML=stages.map((name,i)=>`<button data-view="${i}" ${i>state.stage?'disabled':''} ${i===view?'aria-current="step"':''}><span>${i<state.stage?'✓':String(i+1).padStart(2,'0')}</span>${name}</button>`).join('');
 $('#sample-controls').hidden=!state.sample;$('#sample-next').disabled=![1,3].includes(state.stage);$('#sample-next').textContent=state.stage===1?'Load sample design choices →':state.versions.length?'Load next sample preview →':'Load sample homepage proof →';
 $('#surface').innerHTML=[brief,research,choices,build,review,handoff][view]();
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches){$('#surface').getAnimations().forEach(a=>a.cancel());$('#surface').animate([{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'none'}],{duration:420,easing:'cubic-bezier(.2,.8,.2,1)'});}$('#notice').textContent='';$('#save-state').textContent=storageOK?'Saved on this device':'Storage unavailable — keep this tab open';
 document.querySelectorAll('[data-concept]').forEach(frame=>frame.srcdoc=conceptHTML(frame.dataset.concept,Number(frame.dataset.version)));
 thumbnailObserver.disconnect();document.querySelectorAll('.thumb').forEach(thumb=>thumbnailObserver.observe(thumb));
 $('#brief-form')?.addEventListener('submit',event=>{event.preventDefault();try{const brief=validateBrief({...state.brief,...Object.fromEntries(new FormData(event.target))});act({type:'brief',brief});}catch(error){notice(error.message);}});
 $('#brief-form [name=project_mode]')?.addEventListener('change',event=>{state.brief={...state.brief,...Object.fromEntries(new FormData($('#brief-form'))),project_mode:event.target.value};save();render();$('#brief-form [name=project_mode]').focus();});
 $('#brief-form [name=current_website_url]')?.addEventListener('change',event=>{try{const site=normalizeWebsiteURL(event.target.value);state.brief.current_website_url=site.url;state.brief.domain=site.domain;event.target.value=site.url;save();}catch(error){notice(error.message);}});
 $('#send-form')?.addEventListener('submit',sendBrief);
 $('#edit-brief')?.addEventListener('click',()=>{state.stage=0;view=0;save();render();});
 $('#direction-form')?.addEventListener('submit',event=>{event.preventDefault();act({type:'direction',id:previewDirection,note:new FormData(event.target).get('note')});});
 $('#feedback-form')?.addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.target);previewVersion=null;act({type:'feedback',section:f.get('section'),note:f.get('note')});});
 $('#approval-form')?.addEventListener('submit',event=>{event.preventDefault();act({type:'approve'});});
 $('#download-site')?.addEventListener('click',()=>download('northline-sample.html',conceptHTML(state.selected,state.versions.at(-1).id),'text/html'));
 $('#download-record')?.addEventListener('click',()=>download('sample-project-record.json',JSON.stringify(state,null,2),'application/json'));
}
async function sendBrief(event){
 event.preventDefault();if(busy||state.sample||state.receipt)return;
 const form=event.target,values=Object.fromEntries(new FormData(form));if(!(state.brief.project_mode==='existing'?state.brief.domain:values.domain)?.trim()||!values.contact_email?.trim())return notice('Add your domain and reply email before sending.');
 state.brief={...state.brief,...values};save();let payload;try{payload=briefPayload(state.brief);}catch(error){notice(error.message);return;}busy=true;const button=form.querySelector('button');button.disabled=true;button.textContent='Sending your brief…';
 try{const response=await fetch('https://stromation-production.up.railway.app/website-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok||!result.ok){const details=Array.isArray(result.problems)?result.problems.join(' '):result.error;notice(typeof details==='string'?details.slice(0,600):'The service could not accept this brief. Please check your details and try again.');button.disabled=false;button.textContent='Send brief for scope review →';return;}if(result.duplicate&&!result.id){notice('An open project already exists for this website. Open it in the browser where you started it, or use its project access link. No second project was created.');button.disabled=true;button.textContent='Existing project found';return;}if(!result.id)throw Error('unconfirmed');if(result.project_token)liveSession=saveSession(result);act({type:'receipt',id:String(result.id)});notice(result.duplicate?'An existing brief for this domain was found. Its receipt is shown above.':'Your brief was recorded. Nothing has been charged or started.');}
 catch{notice('We couldn’t confirm the receipt. Your draft is saved here. The request may have arrived; retrying may return the existing brief.');button.disabled=false;button.textContent='Try sending again';}finally{busy=false;}
}
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view!==undefined){view=Number(b.dataset.view);previewVersion=null;render();$('#main').focus();}if(b.dataset.inspect){previewDirection=b.dataset.inspect;render();$('.choice-detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}if(b.dataset.device){const shell=b.closest('.preview-shell');shell.querySelector('.preview-window').className='preview-window '+b.dataset.device;shell.querySelectorAll('[data-device]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}if(b.dataset.versionChoice){previewVersion=Number(b.dataset.versionChoice);render();}});
$('#sample-next').addEventListener('click',()=>{previewVersion=null;act({type:'sample-next'});});

$('#sample-toggle').addEventListener('click',()=>{if(busy)return notice('Wait for the brief submission to finish.');projects[state.sample?'sample':'real']=state;state=projects[state.sample?'real':'sample'];view=state.stage;previewDirection=null;previewVersion=null;save();render();});
$('#reset').addEventListener('click',()=>{if(busy)return notice('Wait for the brief submission to finish.');$('#reset-dialog').showModal();});
$('#cancel-reset').addEventListener('click',()=>$('#reset-dialog').close());$('#confirm-reset').addEventListener('click',()=>{if(!state.sample){clearSession();liveSession=null;}state=fresh(state.sample);view=0;previewDirection=null;previewVersion=null;save();$('#reset-dialog').close();render();});
document.addEventListener('input',event=>{if(event.target.closest('#brief-form')){state.brief={...state.brief,...Object.fromEntries(new FormData($('#brief-form')))};save();}});
document.addEventListener('project-access-expired-reset',()=>{clearSession();liveSession=null;render();notice('The expired session was closed. Your project is still saved on the service; use a fresh project access link to reconnect.');});
render();
